language: node_js
os: osx

node_js:
  - "10"

before_install:
  - cd spider
  - ./fail-if-not-travis-cron.sh
  - npm i -g npm@6

script:
  - ./build-db.sh

cache:
  directories:
    - "spider/node_modules"
    - "spider/db"
