language: node_js
os: osx

node_js:
  - "10"

before_install:
  - cd spider
  - ./fail-if-not-travis-cron.sh

script:
  - ./build-db.sh

cache:
  yarn: true
  directories:
    - "spider/node_modules"
    - "spider/db"
